### ISSUE TITLE
usgs.gov

### ISSUE THREAD

**Issue by ErinKenna** [opendatacube/cube-in-a-box#14]
Just a heads-up that the usgs urls have changed.

e.g.
https://landsat.usgs.gov/pathrow-shapefiles 
probably changed to
https://www.usgs.gov/land-resources/nli/landsat/landsat-path-row-shapefiles-and-kml-files

https://landsat.usgs.gov/sites/default/files/documents/WRS2_descending.zip 
probably changed to 
https://prd-wret.s3-us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/WRS2_descending_0.zip

**Comment by alexgleith** [comment]
Thanks @ErinKenna, I'll look into it.

**Comment by alexgleith** [comment]
Pretty sure this is fixed.

**Comment by ErinKenna** [comment]
Might need to update the readme here as well: https://github.com/opendatacube/cube-in-a-box/blob/master/data/readme.md @alexgleith

**Comment by alexgleith** [comment]
Ah thanks. Done 👍

**Comment by ewirth** [comment]
Dear All, is this shapefile change in content by time? E.g. modified paths, rows?
