### ISSUE TITLE
Add Sentinel 2 product definition and enable indexing of Sentinel 2 from public data bucket

### ISSUE THREAD

**Issue by Tossawon** [opendatacube/cube-in-a-box#21]

**Comment by alexgleith** [comment]
>>>Hi, i have been testing the cube in a box for 2 weeks. It's is very easy to understand. However, i want to change the product from Landsat8 to sentinel2. Do you have any scripts (such as changing ls_public_bucket.py to s2b_public_bucket.py)  or guidelines to use sentinel2?

Original title copied above.

Firstly, @Tossawon, where are you looking to index the S2 data from? From the AWS public dataset bucket?

**Comment by alexgleith** [comment]
This will be successful when there's indexing that works, using the current Sat STAC API method, and includes indexing JPG2000 files.

This should be easy enough.

**Comment by alexgleith** [comment]
This has been done 🎉
