### ISSUE TITLE
GDAL3 support in ls_public_bucket.py script

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/cube-in-a-box#23]
GDAL3 swaps order of Lon/Lat and generated extents are not correct when running this script in the environment with GDAL3 installed.

https://github.com/opendatacube/cube-in-a-box/blob/eb9ffa6c7b287483365d903872457125c606549d/scripts/ls_public_bucket.py#L80-L85

In GDAL3 output of `TransformPoint` is `lat,lon,z` instead. But that code is wrong in other ways, since we need bounding box of the geometry in `EPSG:4326` and not a mere transform or the 4 corners to `ESPG:4326`. This also doesn't work when dataset's footprint spans `lon=180` line.
https://github.com/opendatacube/datacube-core/issues/886

Also shouldn't that script be in `datacube-dataset-config` repo?
https://github.com/opendatacube/datacube-dataset-config/issues/10

**Comment by alexgleith** [comment]
Yes, the script should be in `datacube-dataset-config` and it should be a git submodule. There's a fair bit of consolidation that should be undertaken in the indexing process in this repo.
