### ISSUE TITLE
Swapped x,y coords in GDAL3 case

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/cube-in-a-box#26]
I know it's not merged yet, but I saw this code in Slack, and pretty sure this bit is wrong:

https://github.com/opendatacube/cube-in-a-box/blob/5ea202f8652a075cd7eaebf77257e3164a965dbc/scripts/ls_public_bucket.py#L176

Should be 
```python
    x, y, z = t.TransformPoint(p[1], p[0]) 
```

order of projected coordinates is typically not swapped by CRS definition. 

Also I would strongly suggest extracting and labeling `lon/lat` from `p` rather than using index based access, something like this up top:  `lon, lat = p`, as this then clearly communicates the expected order of coordinates on input to the `transform` function.

**Comment by alexgleith** [comment]
Yeah, you're right.

Here's the working code:
```
        lon, lat = p
        # GDAL 3 reverses coordinate order, because... standards
        if LON_LAT_ORDER:
            # GDAL 2.0 order
            x, y, z = t.TransformPoint(lon, lat)
        else:
            # GDAL 3.0 order
            x, y, z = t.TransformPoint(lat, lon)

        return [x, y]
```

Notes from here: https://github.com/OSGeo/gdal/issues/1546

And an output projected extent that was tested.

![image](https://user-images.githubusercontent.com/3445853/81998381-b473c180-9695-11ea-96f1-18fa189c8acc.png)
