### ISSUE TITLE
Sentinel 2 notebook

### ISSUE THREAD

**Issue by bluetyson** [opendatacube/cube-in-a-box#31]
Hi,

In github.com/opendatacube/cube-in-a-box/blob/master/notebooks/Sentinel_2.ipynb

Tried this from the cube I installed a while ago

import sys
import datacube

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-2976c89801d7> in <module>

      4 
----> 5 from datacube.utils.deafrica_datahandling import load_ard
      6 from datacube.utils.deafrica_plotting import rgb

ModuleNotFoundError: No module named 'datacube.utils.deafrica_datahandling'

Do I need to update the cube in a box?

**Comment by DanielOrtega94** [comment]
Hi, you need import this file https://github.com/opendatacube/cube-in-a-box/blob/master/notebooks/utils/deafrica_datahandling.py

**Comment by bluetyson** [comment]
Thanks Daniel, will give that a go

**Comment by RichardScottOZ** [comment]
Ok, now I see - this version https://github.com/bluetyson/cube-in-a-box-dea I don't think has that folder

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-01835cf183f2> in <module>
      5 import matplotlib.pyplot as plt
      6 #import utils
----> 7 from utils.utils import (
      8     lat_lon_to_epsg,
      9     three_band_image,

ModuleNotFoundError: No module named 'utils'

**Comment by DanielOrtega94** [comment]
> Ok, now I see - this version https://github.com/bluetyson/cube-in-a-box-dea I don't think has that folder
> 
> ModuleNotFoundError Traceback (most recent call last)
> in
> 5 import matplotlib.pyplot as plt
> 6 #import utils
> ----> 7 from utils.utils import (
> 8 lat_lon_to_epsg,
> 9 three_band_image,
> 
> ModuleNotFoundError: No module named 'utils'

yes, that version is a forked old version of this repo

**Comment by RichardScottOZ** [comment]
Thanks Daniel.

**Comment by alexgleith** [comment]
I think this is fixed.

**Comment by RichardScottOZ** [comment]
Ok, will have to give it a shot sometime in the near future.

**Comment by amalsara** [comment]
when we use below 
github.com/opendatacube/cube-in-a-box/blob/master/notebooks/Sentinel_2.ipynb
we faced below error
ModuleNotFoundError: No module named 'utils'
