### ISSUE TITLE
Landsat default dataset file not found

### ISSUE THREAD

**Issue by RichardScottOZ** [opendatacube/cube-in-a-box#33]
In the Cube In a Box magic link setup

+ wget https://landsat.usgs.gov/sites/default/files/documents/WRS2_descending.zip -O /opt/odc/data/wrs2_descending.zip
/opt/odc/data/wrs2_descending.zip: No such file or directory
Cloud-init v. 18.5-45-g3554ffe8-0ubuntu1~18.04.1 running 'modules:final' at Fri, 05 Feb 2021 02:33:52 +0000. Up 57.92 seconds.
2021-02-05 02:35:32,236 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
2021-02-05 02:35:32,237 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2021-02-05 02:35:32,238 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 18.5-45-g3554ffe8-0ubuntu1~18.04.1 finished at Fri, 05 Feb 2021 02:35:32 +0000. Datasource DataSourceEc2Local.  Up 157.24 seconds

comment that out I then get :- mv: cannot move 'cube-in-a-box-master' to '/opt/odc/cube-in-a-box-master': Directory not empty - as already done? - after rerunning the part-001 script again

and I comment that out and create /opt/odc/data I get to this which is probably my fault from multiple runs

Digest: sha256:99cdc036afe01255b329c72a9fca201dea00619f22fd50a24c98f2b1dd4f7891
Status: Downloaded newer image for opendatacube/geobase:runner-3.0.4
 ---> 473834e4aa92
Step 7/16 : ARG py_env_path
 ---> Running in 293a1ae4f53b
Removing intermediate container 293a1ae4f53b
 ---> cb13c9ae7b76
Step 8/16 : COPY --chown=1000:100 --from=env_builder $py_env_path $py_env_path
Error processing tar file(exit status 1): write /env/lib/python3.6/site-packages/skimage/feature/_texture.cpython-36m-x86_64-linux-gnu.so: no space left on device
ERROR: Service 'jupyter' failed to build

**Comment by RichardScottOZ** [comment]
Looks like link to template in s3 doesn't have the 40GB disk size addition, so just use the one here manually.

**Comment by RichardScottOZ** [comment]
And other notes for reference :- ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-983bdcd70800> in <module>
      3 import datacube
      4 from satsearch import Search
----> 5 from odc.apps.dc_tools.stac_api_to_dc import stac_api_to_odc
ModuleNotFoundError: No module named 'odc.apps.dc_tools'

**Comment by RichardScottOZ** [comment]
SSH into the machine. Do cd /opt/odc
Then ls and you should see a docker-compose file.
Please do docker-compose stop then docker-compose pull then docker-compose up -d
Probably all needs sudo

**Comment by RichardScottOZ** [comment]
Dockerfile  cube-in-a-box-cloudformation.yml  notebooks
LICENSE     docker-compose-prod.yml           parameters.json
Makefile    docker-compose.yml                requirements.txt
README.md   docs

**Comment by RichardScottOZ** [comment]
sudo docker-compose -f docker-compose.yml -f docker-compose-prod.yml pull
          sudo docker-compose -f docker-compose.yml -f docker-compose-prod.yml up -d

**Comment by RichardScottOZ** [comment]
Oh, and wait 5 mins before running the pull command...

Successfully built ddfb20c792ea
Successfully tagged odc_jupyter:latest
WARNING: Image for service jupyter was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Starting odc_postgres_1  ... done
Recreating odc_jupyter_1 ... done

**Comment by RichardScottOZ** [comment]
stop, the default version, then this sudo docker-compose -f docker-compose-prod.yml pull
now with the up command do I need to do this with both the compose yml file references?
sudo docker-compose up -d

**Comment by alexgleith** [comment]
I think this is no longer relevant.
