### ISSUE TITLE
Error: Got unexpected extra argument (s2_l2a)

### ISSUE THREAD

**Issue by AndriiKolotii** [opendatacube/cube-in-a-box#40]
After trying to execute 
docker-compose exec jupyter bash -c "stac-to-dc --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs' --datetime='2020-01-01/2020-03-31' s2_l2a"

following error is shown
Error: Got unexpected extra argument (s2_l2a)

In case of editing  as suggested in dcc32a61494c1b43df7633a7424cb88b58d8770c 
following error is raised 
AttributeError: 'ItemSearch' object has no attribute 'get_all_items'

**Comment by alexgleith** [comment]
Sorry about this, it's fixed now.
