### ISSUE TITLE
odc-io installation fails

### ISSUE THREAD

**Issue by LisaKnopp** [opendatacube/cube-in-a-box#42]
```docker-compose up``` fails during installation of odc-io (as part of odc-apps-dc-tools), probably due to a new release (odc-io 0.2).

![grafik](https://user-images.githubusercontent.com/32666778/129113648-7bc6bd2a-5b95-4434-9beb-e46ccce11c02.png)

Modifying the requirements.txt by adding pystac before odc-apps-dc-tools seems to solve the problem.

**Comment by alexgleith** [comment]
Fixed.
