### ISSUE TITLE
Get CloudFormation deployment to use pre-built image

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/cube-in-a-box#44]
The override file `docker-compose-prod.yml` should be used in infrastructure deployments so that we use a pre-built Docker image instead of building on the fly. This will save 5-10 minutes for startup.

**Comment by alexgleith** [comment]
Hey @dominicschaff shall we discuss here?

**Comment by dominicschaff** [comment]
We can.

I added `up-prod` that can do that. So if I make a `setup-prod` then it can use that instead of the current `build` and `up`

**Comment by alexgleith** [comment]
Sounds good to me  👍 

I can tweak the Docker image dependencies and make sure it builds happily. There were a couple of libs conflicting when I built on AWS just now.

**Comment by dominicschaff** [comment]
I didn't notice any conflicts when I was testing. What conflicts were they? I probably missed something

**Comment by alexgleith** [comment]
> ERROR: botocore 1.15.32 has requirement urllib3<1.26,>=1.20; python_version != "3.4", but you'll have urllib3 1.26.6 which is incompatible.
> ERROR: awscli 1.18.32 has requirement PyYAML<5.4,>=3.10; python_version != "3.4", but you'll have pyyaml 5.4.1 which is incompatible.
> ERROR: pystac-client 0.2.0 has requirement requests~=2.25.1, but you'll have requests 2.26.0 which is incompatible.
> ERROR: jupyter-ui-poll 0.1.3 has requirement ipykernel<6, but you'll have ipykernel 6.3.1 which is incompatible.

Python dependencies are a real pain

**Comment by dominicschaff** [comment]
Ah, that is something I did skip.
