### ISSUE TITLE
Open data explorer endpoint in addition to Jupyter port

### ISSUE THREAD

**Issue by romeokienzler** [opendatacube/cube-in-a-box#60]
I'm currently in the process of setting up ODC with the [OpenEO](openeo.org/) [ODC driver](https://github.com/SARScripts/openeo_odc_driver) but noticed that ODC cube in a box only exposes port 8888 of jupyter to the host. 

I've noticed that there are quite some python3 processes opening tcp port on localhost:

> !netstat -anp |grep tcp |grep LISTEN
> tcp        0      0 127.0.0.1:53257         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 127.0.0.1:52043         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 127.0.0.1:60323         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 127.0.0.1:34277         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 127.0.0.1:36557         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 127.0.0.11:36147        0.0.0.0:*               LISTEN      -                   
> tcp        0      0 127.0.0.1:42367         0.0.0.0:*               LISTEN      187/python3         
> tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      7/python3 

> !nmap -sS -p- 127.0.0.1 |grep tcp |awk -F"/" '{print $1}' | sort
> 34277
> 36557
> 42367
> 52043
> 53257
> 60323
> 8888

But connecting to those I realized that they are not HTTP ports:

> !for port in `nmap -sS -p- 127.0.0.1 |grep tcp |awk -F"/" '{print $1}' | sort`; do echo 'GET / HTTP1.1\n' | telnet localhost $port; 
> done
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.

So I'm actually wondering how the following code works at all (need to dig into the source code still)

`dc = datacube.Datacube(app='Sentinel_2')`

If I know which port to open or what is needed to tell ODC to opten the data explorer endpoint I can adjust the compose yaml to make it work

**Comment by clausmichele** [comment]
Hi @romeokienzler, I'm actually restructuring the openeo_odc_driver project and trying to create a Docker based on cube-in-a-box 👍

**Comment by romeokienzler** [comment]
Oh wow, thanks a lot @clausmichele looking forward

**Comment by clausmichele** [comment]
Starting from the nice Docker deployment of cube-in-a-box I realized one for our project which is also starting datacube-explorer as a service here:
https://github.com/SARScripts/openeo_odc_driver/tree/dev

It could be easily integrated in cube-in-a-box as well.

**Comment by romeokienzler** [comment]
Thanks @clausmichele I confirm ODC works from what you've provided above, so I'm happy and close - feel free to re-open in case you want to integrate in cube-in-a-box
